### ISSUE TITLE
Broken Docs Example

### ISSUE THREAD

**Issue by TylerSustare** [apollographql/community#35]
The `Code Sandbox` link [here](https://codesandbox.io/s/nn9y2wzyw4) from the getting started section [here](https://www.apollographql.com/docs/react/essentials/get-started.html#installation) is broken. 

I noticed a network error when following along, but it looks like the ~CodePen~ CodeSandbox example is broken as well. It's reassuring it isn't just me, but would be nice to see what it's supposed to look like. 

![image](https://user-images.githubusercontent.com/10850753/45002913-2030fc00-af91-11e8-8c2c-d83a924a9b0f.png)

**Comment by itstimetogoleft** [comment]
The [CodeSandbox example](https://codesandbox.io/s/nn9y2wzyw4) is working now! This issue should be closed.

**Comment by hwillson** [comment]
Thanks @itstimetogoleft!
